name: My First Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runner type (could be macOS, Windows, or Ubuntu)

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # This action checks out your code

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Sets up Node.js if your project uses it
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install  # Install your project dependencies

    - name: Run tests
      run: npm test  # Run your tests

    - name: Commit any changes
      run: git commit -am "Automated changes" || echo "No changes to commit"
